apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-k8s

spec:
  selector:
    matchLabels:
      app: demo-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: demo-k8s
    spec:
      containers:
        - name: demo-k8s
          image: demo-k8s:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: test_db
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: Believeingod01!

---
apiVersion: v1
kind: Service
metadata:
  name: demo-k8s
spec:
  selector:
    app: demo-k8s
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort